# -*- coding: utf-8 -*-
"""Working-with-csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_ol3LYmuyVG1rmzXoJAyxKP5_BF-ITU

#**Import pandas**
"""

import pandas as pd

"""#**Openeing a local csv file from own laptop**"""

df=pd.read_csv('/content/placement.csv')

df.head()

"""#**Opening a csv file from an URL**"""

import requests
from io import StringIO
url ="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv: 66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)
pd.read_csv(data)

"""#**Sep parameter**
##used to tell that how our data is separated by.
##eg: csv(comma separted),tsv(tap separated)
"""

pd.read_csv('/content/titanic.tsv')

pd.read_csv('/content/titanic.tsv',sep='\t',names=['PassengerId','Survived','Pclass','Name','Sex','Age','SibSp','Parch','Ticket','Fare','Cabin','Embarked'])

"""#**Index_col parameter**
# remove google collab index with your index which is present in dataset
"""

pd.read_csv('/content/titanic.tsv',sep='\t',names=['PassengerId','Survived','Pclass','Name','Sex','Age','SibSp','Parch','Ticket','Fare','Cabin','Embarked'],index_col='PassengerId')

"""##**use_cols parameter**
## if we want to use only few cols from dataset
"""

pd.read_csv('/content/placement.csv')

pd.read_csv('/content/placement.csv',usecols=['cgpa','iq','placement'])

"""#**skiprows/nrows parameter**"""

pd.read_csv('/content/placement.csv',skiprows=[0,1])

"""#**loading a huge dataset in chunks**"""

dfs=pd.read_csv('/content/placement.csv',chunksize=20)

for chunks in dfs:
   print(chunks.shape)