# -*- coding: utf-8 -*-
"""end-to-end-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f40uSSVY7pMHZYCKqv0ikaBXElKnmUik

**IMPORT LIBRARY**
"""

# **Steps**
# 1-> Preprocess + EDA + Feature Selection
# 2-> Extract input and output
# 3-> Scale the values
# 4-> Train test split
# 5-> Train the model
# 6-> Evaluate the model/model selection
# 7-> Deploy the model

import numpy as np
import pandas as pd

df=pd.read_csv('/content/placement.csv')

df.head()

df.shape

df = df.iloc[:,1:]

df.info()

df.isnull().sum()

df.head()

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

# After Seeing the graph(EDA), we say that logistic regression
# (divide the graph into 2 parts using a single line)
# will be good model

"""#**Extract input and output**"""

X=df.iloc[:,:2]
y=df.iloc[:,-1]

X

y

y.shape

"""#**Train test split**"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=2)

X_train

y_train

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)

X_train

X_test=scaler.transform(X_test)

X_test

"""#**Model Training**"""

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

y_predict=model.predict(X_test)

y_predict

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X_train,y_train.values,clf=model,legend=2)

import pickle

pickle.dump(model,open('model.pkl','wb'))